### ISSUE TITLE
send() for text?

### ISSUE THREAD

**Issue by jhihn** [MichaelNeas/perpetual-learning#12]
In your send function, you explicitly code it for .binary. How would someone send text?  CI can't seem to figure out what to do after setting opcode to .text.

The NWConnection object doesn't seem text friendly? It'l take a "content", but then String does not conform to DataProtocol.

How can we send text with it?

**Comment by MichaelNeas** [comment]
@jhihn I'm assuming you're talking about `send(data: Data)` in `SwiftWebSocketServer.swift` ?

Sending a `String` would be a convenience as everything will need to be encoded and serialized at the end of the day for the communication protocol.  Why not use the `Data(base64encode)` initializer?

**Comment by jhihn** [comment]
Yes. 

Because I am (trying) to work with a client that is already implemented (not in swift) that expects text messages over WebSocket. If I can't figure out how to send text messages to the client then I can't use this :-( 

I'm talking about text as in: 
https://tools.ietf.org/html/rfc6455 Section "5.6 Data Frames"

**Comment by MichaelNeas** [comment]
@jhihn 

Could you try to modify this line: https://github.com/MichaelNeas/perpetual-learning/blob/master/ios-sockets/SwiftWebSocketServer/SwiftWebSocketServer/SwiftWebSocketServer.swift#L146

To be `opcode: .text`

The connection send method provided by apple requires either Data or something that conforms to DataProtocol. 

Maybe try `Data(text.utf8)` and pass it in to the `connection.send`.  I'm not sure what text encoding your client is expecting, but the opcode change should allow the data to at least be accepted be the client!

Let me know what you find out 😄

**Comment by jhihn** [comment]
So there's a few issues here, because I am new to Swift. I assumed I was doing something wrong. 

Firstly, you never set `self.connection = connection` in `didAccept()`.  So when you call `send()`, `self.connection?.send(data: data)` doesn't actually send because self.connection is still nil.

Next I provided an overload for send() as:
```
    func send(data: String) {
		print("send(data: String)", data)
        let metaData = NWProtocolWebSocket.Metadata(opcode: .text)
        let context = NWConnection.ContentContext (identifier: "context", metadata: [metaData])
		self.connection.send(content: data.data(using: .utf8), contentContext: context, isComplete: true, completion: .contentProcessed( { error in
            if let error = error {
                self.connectionDidFail(error: error)
                return
            }
            print("connection \(self.id) did send, data: \(data as String)")
        }))
   }
```
it seems you need the `.data(using: .utf8)` bit and not `.utf8`, because `String.View` does not support `DataProtocol`


With those modifications, I can now send a message to the client.
Please advise if I did something wrong, as I'm new to Swift.

**Comment by MichaelNeas** [comment]
@jhihn that seems to be good! Thanks for finding the `self.connection = connection` bit! If you want to add that and PR it in to the repo I'd appreciate it! 

Very happy you were able to send a message to the client!

**Comment by MichaelNeas** [comment]
hope that helped @jhihn , going to close this

**Comment by jhihn** [comment]
Yes, it did. Thank you.
