### ISSUE TITLE
__nw_frame_claim message?

### ISSUE THREAD

**Issue by jhihn** [MichaelNeas/perpetual-learning#16]
Whenever I send I get these messages:

[] __nw_frame_claim Claiming bytes failed because start (41) is beyond end (0 - 0)
[] __nw_frame_claim Claiming bytes failed because start (120) is beyond end (0 - 0)

Where 41, 120 are the lengths of the message. Any idea what is happening there?

**Comment by MichaelNeas** [comment]
@jhihn Is that a warning or an error? If i would guess it has something to do with memory allocation, but that's a guess.
The only link I've found where someone experienced something similar is: https://developer.apple.com/forums/thread/133442

**Comment by jhihn** [comment]
It seems to just be a warning. It's really annoying. But at least I'm not the only one with it. :-)

**Comment by MichaelNeas** [comment]
@jhihn try out new main branch, @danielrbrowne made some awesome additions to allow us to use a lower level version `NWWebSocket`That warning might go away for you
