### ISSUE TITLE
Network.framework implementation of NativeWebSocket.swift

### ISSUE THREAD

**Issue by danielrbrowne** [MichaelNeas/perpetual-learning#17]
I have recently been implementing a WebSocket client based on `URLSessionWebSocketTask`. This has worked well, however the limitation of `URLSessionWebSocketTask.CloseCode` is that it has no way to define custom close codes (as compared to `NWProtocolWebSocket.CloseCode`). I am working on a WebSocket application that issues close codes in the 4000 - 4999 range as well as the standard defined codes, so I need my client implementation to have knowledge of these codes as well.

I have of course seen `SwiftWebSocketServer.swift`, using `Network`, however given the lack of examples and docs out there on using `NWProtocolWebSocket`, I am wondering if you could suggest an implementation of `NativeWebSocket.swift` using the lower-level `Network` objects so that these custom close codes can be surfaced?

**Comment by MichaelNeas** [comment]
@danielrbrowne  I think you're correct in needing to drop into `Network` for the private close codes.

Writing a custom client will be a bunch of trial and error, as I didn't find many examples myself.

I'm open to helping out if you wanted to fork and play around with implementing a lower level client.

**Comment by danielrbrowne** [comment]
@MichaelNeas Thanks for the input - I have been having some limited success so far and I will aim to have something up for review in a PR by early next week. Would definitely welcome your input on my implementation so far...
