### ISSUE TITLE
Memory leak in ServerConnection

### ISSUE THREAD

**Issue by joonaservald** [MichaelNeas/perpetual-learning#24]
Thanks for the article! I was playing around with the code and noticed a memory leak.

`ServerConnection` sometimes leaks on the server side. Not 100% sure what caused it as I just changed all the `self` captures to `weak` and made sure that `didReceive` callback was also cleared on connection end. No more leak! I thought maybe someone else might find this useful.

**Comment by MichaelNeas** [comment]
nice find!

Want to submit a PR??

**Comment by joonaservald** [comment]
Voilà! 🎉
